sudo: required
services:
    - docker 

before_install:
    -sudo docker build -t vadimsdocker/docker-ract -f Dockerfile.dev .


script:
  - sudo docker run vadimsdocker/docker-ract npm run test -- --coverage