sudo: required
services:
    - docker 

before_install:
    - docker build -t vadimsdocker/docker-ract -f Dockerfile.dev .


script:
  - docker run vadimsdocker/docker-ract npm run test -- --coverage