sudo: required
services:
    - docker 


before_install:
    - docker build -t vadimsdocker/docker-ract -f Dockerfile.dev .



script:
   - docker run vadimsdocker/docker-ract npm run test -- --coverage


deploy:
   provider: elasticbeanstalk
   region: "eu-west-3"
   app: "docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-test1"
   bucket_path: "docker"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: "$AWS_SECRET_KEY"